from .hospital_view import HospitalViewSet
from .hospital_inventory_views import HospitalInventoryView, HospitalInventoryDetailView, HospitalInventoryBulkAddView
from .hospital_sales_view import HospitalSalesView, HospitalSalesDetailView
from .hospital_operations_view import HospitalOperationsDetailView, HospitalOperationsView
from .hospital_analyses_views import HospitalAnalysesView, HospitalAnalysesDetailView

from .hospital_stats_view import HospitalStatsView
from .hospital_tickets_view import HospitalTicketView, HospitalTicketsDetailView
from .hospital_payments_view import HospitalPaymentsView, HospitalPaymentsDetailView, PaymentViewSet