# Generated by Django 4.1.6 on 2023-11-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentsaleitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
