# Generated by Django 4.1.6 on 2023-12-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_ticket'),
        ('transacations', '0002_ticketaction_payment_operationaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='entity.hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='is_valid',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
