# Generated by Django 4.1.6 on 2023-11-13 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0009_alter_hospital_assigneduser'),
        ('transacations', '0002_alter_medicamentsaleitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentsale',
            name='hospital',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='entity.hospital'),
            preserve_default=False,
        ),
    ]
