# Generated by Django 4.1.6 on 2023-12-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0004_ticketaction_insurance_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketaction',
            name='patient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='quittance_number',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
