# Generated by Django 4.1.6 on 2023-12-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0007_alter_payment_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketaction',
            name='today_id',
        ),
        migrations.AlterField(
            model_name='ticketaction',
            name='patient',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
