# Generated by Django 4.1.6 on 2023-12-19 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0008_remove_ticketaction_today_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationaction',
            name='planned_date_time',
        ),
    ]
