# Generated by Django 4.1.6 on 2023-12-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0009_remove_operationaction_planned_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationaction',
            name='today_id',
        ),
        migrations.AddField(
            model_name='operationaction',
            name='insurance_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
