# Generated by Django 4.1.6 on 2023-12-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0011_analyseaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyseaction',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operationaction',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
