# Generated by Django 4.1.6 on 2023-12-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0012_alter_analyseaction_insurance_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseaction',
            name='patient',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
