# Generated by Django 4.1.6 on 2023-12-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0013_analyseaction_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyseaction',
            name='today_id',
        ),
        migrations.AddField(
            model_name='operationaction',
            name='patient',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
