# Generated by Django 4.1.6 on 2023-12-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0014_remove_analyseaction_today_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyseaction',
            name='planned_date_time',
        ),
    ]
