# Generated by Django 4.1.6 on 2023-12-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0016_medicamentsale_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationaction',
            name='price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketaction',
            name='price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
