# Generated by Django 4.1.6 on 2023-12-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0017_operationaction_price_ticketaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseaction',
            name='price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
