# Generated by Django 4.1.6 on 2023-12-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_remove_medicamentcategory_hospital_and_more'),
        ('transacations', '0019_remove_analyseaction_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentsaleitem',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='entity.medicament'),
        ),
    ]
