# Generated by Django 4.1.6 on 2023-12-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0020_alter_medicamentsaleitem_medicament'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketaction',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
