# Generated by Django 4.1.6 on 2023-12-25 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0013_client_hospital_show_in_subs_and_more'),
        ('transacations', '0021_ticketaction_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_actions', to='entity.client'),
        ),
        migrations.AlterField(
            model_name='ticketaction',
            name='patient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
