# Generated by Django 4.1.6 on 2023-12-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0023_remove_payment_created_by_remove_payment_is_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.CharField(default='77.01', max_length=255),
            preserve_default=False,
        ),
    ]
