# Generated by Django 4.1.6 on 2023-12-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0024_payment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='for_pharmacy',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
