# Generated by Django 4.1.6 on 2024-01-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0025_payment_for_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseaction',
            name='is_taazour_insurance',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamentsale',
            name='is_taazour_insurance',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationaction',
            name='is_taazour_insurance',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketaction',
            name='is_taazour_insurance',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
