# Generated by Django 4.1.6 on 2024-01-03 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0018_remove_medicament_codebarres'),
        ('transacations', '0026_analyseaction_is_taazour_insurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyseaction',
            name='analyse',
        ),
        migrations.RemoveField(
            model_name='analyseaction',
            name='price',
        ),
        migrations.CreateModel(
            name='AnalyseActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_actions', to='entity.analyses')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_action_items', to='transacations.analyseaction')),
            ],
        ),
    ]
