# Generated by Django 4.1.6 on 2024-01-04 14:31

from django.db import migrations, models

def set_initial_payed_price(apps, schema_editor):
    Ticket = apps.get_model('transacations', 'ticketaction')
    for obj in Ticket.objects.all():
        if obj.insurance_number is None:
            obj.payed_price = obj.price * (obj.duration if obj.duration else 1 )
        else:
            obj.payed_price = obj.price  * (obj.duration if obj.duration else 1 ) * (0 if obj.is_taazour_insurance else 0.1 )
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0029_operationaction_payed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketaction',
            name='payed_price',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operationaction',
            name='payed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.RunPython(set_initial_payed_price),
    ]
