# Generated by Django 4.1.6 on 2024-01-04 14:40

from django.db import migrations, models

def set_initial_payed_price(apps, schema_editor):
    AnalyseActionItem = apps.get_model('transacations', 'AnalyseActionItem')
    for obj in AnalyseActionItem.objects.all():
        if obj.parent.insurance_number is None:
            obj.payed_price = obj.price
        else:
            obj.payed_price = obj.price * (0 if obj.parent.is_taazour_insurance else 0.1 )
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0030_ticketaction_payed_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseactionitem',
            name='payed_price',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.RunPython(set_initial_payed_price),

    ]
