# Generated by Django 4.1.6 on 2024-01-04 14:52

from django.db import migrations


def set_initial_payed_price(apps, schema_editor):
    AnalyseActionItem = apps.get_model('transacations', 'AnalyseActionItem')
    for obj in AnalyseActionItem.objects.all():
        if obj.parent.insurance_number == "":
            parent = obj.parent
            parent.insurance_number = None
            parent.save()
        if obj.parent.insurance_number is None or obj.parent.insurance_number == "":
            obj.payed_price = obj.price
        else:
            obj.payed_price = obj.price * (0 if obj.parent.is_taazour_insurance else 0.1 )
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0031_analyseactionitem_payed_price'),
    ]

    operations = [
    
        migrations.RunPython(set_initial_payed_price),
    ]
