# Generated by Django 4.1.6 on 2024-01-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0033_medicamentsaleitem_payed_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyseactionitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='medicamentsaleitem',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='operationaction',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticketaction',
            name='price',
        ),
    ]
