# Generated by Django 4.1.6 on 2024-01-05 12:30

from django.db import migrations, models

from transacations.models.medicament_sale_item import MedicamentSaleItem


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0034_remove_analyseactionitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyseactionitem',
            name='payed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicamentsaleitem',
            name='payed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
