# Generated by Django 4.1.6 on 2024-01-05 12:32

from django.db import migrations

from transacations.models.medicament_sale_item import MedicamentSaleItem
from django.db import models

def fix_sales_payed_price(apps, schema_editor): 
    salesItem = MedicamentSaleItem.objects.all()
    for item in salesItem:
        item.payed_price = item.medicament.price * item.quantity
        item.save()
class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0035_alter_analyseactionitem_payed_price_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_sales_payed_price)
    ]
