# Generated by Django 4.1.6 on 2024-01-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0036_auto_20240105_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketaction',
            name='payed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
