# Generated by Django 4.1.6 on 2024-01-07 14:35

from django.db import migrations, models

def update_insurance_name(apps, schema_editor):
    AnalyseAction = apps.get_model('transacations', 'AnalyseAction')
    for analyse_action in AnalyseAction.objects.all():
        if analyse_action.is_taazour_insurance:
            analyse_action.insurance_name = 'TAAZOUR'
        else:
            analyse_action.insurance_name = 'CNAM'
        analyse_action.save()

class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0037_alter_ticketaction_payed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseaction',
            name='insurance_name',
            field=models.CharField(blank=True, choices=[('CNAM', 'CNAM'), ('TAAZOUR', 'TAAZOUR'), ('HILAL', 'HILAL')], max_length=255, null=True),
        ),
        migrations.RunPython(update_insurance_name),
    ]
