# Generated by Django 4.1.6 on 2024-01-07 15:31

from django.db import migrations, models

def update_insurances_names(apps, schema_editor):
    MedicamentSale = apps.get_model('transacations', 'medicamentsale')
    for sale in MedicamentSale.objects.all():
        if sale.is_taazour_insurance:
            sale.insurance_name = 'TAAZOUR'
        else:
            sale.insurance_name = 'CNAM'
        sale.save() 
    
    OperationAction = apps.get_model('transacations', 'operationaction')
    for operation_action in OperationAction.objects.all():
        if operation_action.is_taazour_insurance:
            operation_action.insurance_name = 'TAAZOUR'
        else:
            operation_action.insurance_name = 'CNAM'
        operation_action.save()
    TicketAction = apps.get_model('transacations', 'ticketaction')  
    for ticket_action in TicketAction.objects.all():
        if ticket_action.is_taazour_insurance:
            ticket_action.insurance_name = 'TAAZOUR'
        else:
            ticket_action.insurance_name = 'CNAM'
        ticket_action.save()

class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0038_analyseaction_insurance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentsale',
            name='insurance_name',
            field=models.CharField(blank=True, choices=[('CNAM', 'CNAM'), ('TAAZOUR', 'TAAZOUR'), ('HILAL', 'HILAL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='operationaction',
            name='insurance_name',
            field=models.CharField(blank=True, choices=[('CNAM', 'CNAM'), ('TAAZOUR', 'TAAZOUR'), ('HILAL', 'HILAL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketaction',
            name='insurance_name',
            field=models.CharField(blank=True, choices=[('CNAM', 'CNAM'), ('TAAZOUR', 'TAAZOUR'), ('HILAL', 'HILAL')], max_length=255, null=True),
        ),
        migrations.RunPython(update_insurances_names),
    ]
