# Generated by Django 4.1.6 on 2024-01-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0040_remove_medicamentsale_is_taazour_insurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyseaction',
            name='is_taazour_insurance',
        ),
    ]
