# Generated by Django 4.1.6 on 2026-04-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacations', '0043_insurancepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyseaction',
            name='insurance_name',
            field=models.CharField(blank=True, choices=[('CNAM', 'CNAM'), ('TAAZOUR', 'TAAZOUR'), ('HILAL', 'HILAL'), ('CNASS', 'CNASS')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicamentsale',
            name='insurance_name',
            field=models.CharField(blank=True, choices=[('CNAM', 'CNAM'), ('TAAZOUR', 'TAAZOUR'), ('HILAL', 'HILAL'), ('CNASS', 'CNASS')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operationaction',
            name='insurance_name',
            field=models.CharField(blank=True, choices=[('CNAM', 'CNAM'), ('TAAZOUR', 'TAAZOUR'), ('HILAL', 'HILAL'), ('CNASS', 'CNASS')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticketaction',
            name='insurance_name',
            field=models.CharField(blank=True, choices=[('CNAM', 'CNAM'), ('TAAZOUR', 'TAAZOUR'), ('HILAL', 'HILAL'), ('CNASS', 'CNASS')], max_length=255, null=True),
        ),
    ]
