# Generated by Django 4.1.6 on 2023-12-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='has_duration',
        ),
        migrations.AddField(
            model_name='ticket',
            name='duration_type',
            field=models.SmallIntegerField(blank=True, max_length=255, null=True),
        ),
    ]
