# Generated by Django 4.1.6 on 2023-11-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_medicamentcategory_medicament_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='codebarres',
            field=models.CharField(default='AQBBABABQB', max_length=255),
        ),
    ]
