# Generated by Django 4.1.6 on 2023-11-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_medicament_codebarres'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentcategory',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicament_categories', to='entity.hospital'),
            preserve_default=False,
        ),
    ]
