# Generated by Django 4.1.6 on 2023-12-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_remove_ticket_has_duration_ticket_duration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
