# Generated by Django 4.1.6 on 2023-11-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_operationcategory_alter_medicamentcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='code',
            field=models.CharField(default='aaaaaaaaa', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
