# Generated by Django 4.1.6 on 2023-11-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_operations_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='duration',
            field=models.PositiveIntegerField(default=90, max_length=255),
            preserve_default=False,
        ),
    ]
