# Generated by Django 4.1.6 on 2023-12-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_hospital_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentcategory',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='operationcategory',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='analyses',
            name='category',
        ),
        migrations.RemoveField(
            model_name='analyses',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='description',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='category',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='description',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='duration',
        ),
        migrations.AlterField(
            model_name='medicament',
            name='codebarres',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AnalyseCategory',
        ),
        migrations.DeleteModel(
            name='MedicamentCategory',
        ),
        migrations.DeleteModel(
            name='OperationCategory',
        ),
    ]
