# Generated by Django 4.1.6 on 2023-12-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_remove_medicamentcategory_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyses',
            name='code',
        ),
    ]
