# Generated by Django 4.1.6 on 2023-11-11 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0007_operations_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='assignedUser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to=settings.AUTH_USER_MODEL),
        ),
    ]
