# Generated by Django 4.1.6 on 2023-12-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0009_remove_operations_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
