# Generated by Django 4.1.6 on 2023-12-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0010_ticket_is_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='required_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
