# Generated by Django 4.1.6 on 2023-11-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0010_analysecategory_analyses'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='doctor',
            field=models.CharField(default='Doctor 1', max_length=255),
        ),
    ]
