# Generated by Django 4.1.6 on 2023-11-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0011_operations_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysecategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analyses',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analyses',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicamentcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='operationcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='operations',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='operations',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
