# Generated by Django 4.1.6 on 2023-12-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0014_ticket_is_hospital_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
