# Generated by Django 4.1.6 on 2023-12-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0015_hospital_specialization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionAction',
        ),
    ]
