# Generated by Django 4.1.6 on 2023-12-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0016_delete_subscriptionaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='bank_account',
            field=models.CharField(default='77.01', max_length=255),
            preserve_default=False,
        ),
    ]
