# Generated by Django 4.1.6 on 2023-12-30 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0017_hospital_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='codebarres',
        ),
    ]
