# Generated by Django 4.1.6 on 2024-01-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0018_remove_medicament_codebarres'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyses',
            name='insurance_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='insurance_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='insurance_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
