# Generated by Django 4.1.6 on 2024-01-04 23:31

from django.db import migrations

def update_created_at_for_all_hospital_tickets(apps, schema_editor):
    hospitals = apps.get_model("entity", "Hospital").objects.all()
    for hospital in hospitals:
        hospital.created_at ="2024-01-01"

class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0019_analyses_insurance_price_operations_insurance_price_and_more'),
    ]

    operations = [
        migrations.RunPython(update_created_at_for_all_hospital_tickets),
    ]
