# Generated by Django 4.1.6 on 2024-01-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0020_auto_20240104_2331'),
        ('entity', '0021_auto_20240104_2337'),
    ]

    operations = [
    ]
