# Generated by Django 4.1.6 on 2024-01-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0022_merge_0020_auto_20240104_2331_0021_auto_20240104_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='ticket_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
