# Generated by Django 4.1.6 on 2024-01-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0023_hospital_ticket_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=255)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.director')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalTaxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='municipal_tax_data', to='entity.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='municipal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='entity.municipaltaxdata'),
        ),
        migrations.CreateModel(
            name='Alimentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.director')),
            ],
        ),
    ]
