# Generated by Django 4.1.6 on 2024-01-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0025_alter_refund_amount_municipaltaxcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MunicipalTaxCategory',
        ),
    ]
