# Generated by Django 4.1.6 on 2024-01-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0026_delete_municipaltaxcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='category',
        ),
    ]
