# Generated by Django 4.1.6 on 2024-01-12 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0027_remove_refund_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentations', to=settings.AUTH_USER_MODEL),
        ),
    ]
