# Generated by Django 4.1.6 on 2024-01-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0029_refund_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipaltaxdata',
            name='accounts',
            field=models.JSONField(default={
                "category_1": "72.01",
                "category_2": "72.02",
                "category_3": "72.03",

            }),
            preserve_default=False,
        ),
    ]
