# Generated by Django 4.1.6 on 2026-04-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0030_municipaltaxdata_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='cnass_price_patient',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='cnass_total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
