# Generated by Django 4.1.6 on 2026-04-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0031_operations_cnass_price_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cnass_price_patient',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cnass_total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
